### ISSUE TITLE
Windows - Unable to clone repository due to name conflict

### ISSUE THREAD

**Issue by ogdenpm** [tommythorn/virtual-nascom#18]
The file programs/e1000/ROM?-CGSARGON.NAS prevents cloning of the repository on Windows.
The ? in the name is illegal in windows and git clone fails because of it.
A simple rename would fix this e.g. ROM#-CGSARGON.NAS would be ok.

**Comment by tommythorn** [comment]
Thanks, I'll fix it (I don't recall how that got there)
