### ISSUE TITLE
Errors in the simz80.c code

### ISSUE THREAD

**Issue by dallday** [tommythorn/virtual-nascom#6]
Hi - thanks for a brilliant Nascom 2 Emulator - allows me to test stuff before porting it to the real deal.

In checking the code I found some errors in simz80.c code. 

Line 2198 - the INI command
It is decrementing the BC register but it should be just decrementing the B register, and it's not setting the Z flag.

Line 2203 - the OUTI command
The decrement of B is actually decrementing C and putting it in B
It should then be checking if B is zero.
 **Sethreg(BC, lreg(BC) - 1);**  should be **Sethreg(BC, hreg(BC) - 1);**
**SETFLAG(Z, lreg(BC) == 0);** should be **SETFLAG(Z, hreg(BC) == 0);**

Line 2228 - the IND command  - same issue as with OUTI 

Line 2234 - the OUTD command  -same issue as with OUTI

Not sure if you are amending this file directly or still generating it from the perl script.

Kind regards
David

**Comment by tommythorn** [comment]
Hi David,

That's an amazing find, thanks.  I didn't actually write the Z80 interpreter but lifted from something else (I can't remember at the moment), but I'll get this fixed.

**Comment by tommythorn** [comment]
I don't have an easy way to test it but if it looks good to you, I'll push it.

**Comment by dallday** [comment]
it was from yaze Z80 emulator. There he generated the simz80.c from a perl script but having checked his latest version the bugs still seem to be there. And the his perl script does not seem to quite generate the simz80.c file. He has added some fixes to his generated code.

I agree it's not easy one to test, and probably not used very often in code, but the changes look good to me.
