### ISSUE TITLE
problem with OUT (C),B

### ISSUE THREAD

**Issue by dallday** [tommythorn/virtual-nascom#8]
Hi Tommy 
Think I've found another issue in the simz80.c code.

The OUT (C),B and OUT (C),C do not seem to output the correct value to the ports.

The 2 bits of code are

simx80.c

        case 0x41:            /* OUT (C),B */
            Output(lreg(BC), BC);
            break;

        case 0x49:            /* OUT (C),C */
            Output(lreg(BC), BC);
            break;

and should be

        case 0x41:            /* OUT (C),B */
            Output(lreg(BC), hreg(BC));
            break;

        case 0x49:            /* OUT (C),C */
            Output(lreg(BC), lreg(BC));
            break;

to ensure the correct value is sent to the out port 

Stay safe 
David

**Comment by dallday** [comment]
Sorry just spotted that the same issue goes for other OUT (C) opcodes. Where it is the lreg it does work but only because the value is truncated to a single byte.

		case 0x51:			/* OUT (C),D */
			Output(lreg(BC), DE);
			break;

		case 0x79:			/* OUT (C),A */
			Output(lreg(BC), AF);
			break;

		case 0x69:			/* OUT (C),L */
			Output(lreg(BC), HL);
			break;
		case 0x61:			/* OUT (C),H */
			Output(lreg(BC), HL);
			break;
		case 0x59:			/* OUT (C),E */
			Output(lreg(BC), DE);
			break;

**Comment by tommythorn** [comment]
Thanks David, this is a great find and I'm really disappointed in the Z80 engine which I had assumed of better quality.  I'll get these fixed.

**Comment by tommythorn** [comment]
I accidentally wrote “FIX”, not “Fix” so github.com didn’t pick up the commit 69ed428a6608601963a914a09201e2470d45364a
